#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-antrun-plugin
Version  : 1.8
Release  : 3
URL      : https://github.com/apache/maven-antrun-plugin/archive/maven-antrun-plugin-1.8.tar.gz
Source0  : https://github.com/apache/maven-antrun-plugin/archive/maven-antrun-plugin-1.8.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.8/maven-antrun-plugin-1.8.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.8/maven-antrun-plugin-1.8.pom
Source3  : https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.7/maven-antrun-plugin-1.7.jar
Source4  : https://repo1.maven.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.7/maven-antrun-plugin-1.7.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maven-antrun-plugin-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-maven-antrun-plugin package.
Group: Data

%description data
data components for the mvn-maven-antrun-plugin package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.8
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.8
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.8

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.7
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.7

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.7
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.7


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.7/maven-antrun-plugin-1.7.jar
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.7/maven-antrun-plugin-1.7.pom
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.8/maven-antrun-plugin-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-antrun-plugin/1.8/maven-antrun-plugin-1.8.pom
