#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-antrun-plugin
Version  : 1.8
Release  : 1
URL      : https://github.com/apache/maven-antrun-plugin/archive/maven-antrun-plugin-1.8.tar.gz
Source0  : https://github.com/apache/maven-antrun-plugin/archive/maven-antrun-plugin-1.8.tar.gz
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.8/maven-antrun-plugin-1.8.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-antrun-plugin/1.8/maven-antrun-plugin-1.8.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0

%description
No detailed description available

%prep

%build

%install

%files
%defattr(-,root,root,-)
